stages:
  - test

Test static analysis:
  tags:
    - flutter
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
    SONAR_HOST_URL: "https://sonarqube.devpayever.com"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - pwd
    - ls -la
    - export PATH="$PATH:/opt/sonarscanner/bin"
    - export PATH="$PATH:/usr/lib/dart/bin"
    - flutter clean
    - flutter pub get
    - flutter test --machine > tests.output 2>/dev/null || FAILED=true
    - flutter test --coverage 2>/dev/null || FAILED=true
    - cat tests.output
    - ls -la
    - export SONAR_SCANNER_OPTS="-Xmx4096m"
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=${CI_PROJECT_PATH_SLUG} -Dsonar.sources=lib -Dsonar.tests=test -Dsonar.sourceEncoding=UTF-8
