name: payever
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  shared_preferences: ^0.5.8
  path_provider: ^1.6.11
  page_transition: ^1.1.5
  chartjs: ^0.5.1
  flutter_sparkline: ^0.1.0
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  intl: ^0.16.1
  url_launcher: ^5.1.0
  #webview_flutter: ^0.3.10+3
  video_player: ^0.10.11+2
  cached_network_image: ^2.2.0+1
  device_info: ^0.4.2+4
  graphql_flutter: ^3.0.1
  uuid: ^2.2.0
  flutter_masked_text: ^0.8.0
  autocomplete_textfield: ^1.7.3
  numberpicker: ^1.2.0
  cron: ^0.2.3
  flutter_webview_plugin: ^0.3.11
  flutter_pagewise: ^1.2.3
  carousel_slider: ^2.2.1
  flutter_swiper: ^1.1.6
  dio: ^3.0.9
  image_picker: ^0.6.7+4
  provider: ^4.1.3
  rxdart: ^0.24.1
  oktoast: ^2.3.2
  package_info: ^0.4.1
  flutter_html: ^1.0.0
  blurrycontainer: ^0.0.1
  flutter_inner_drawer: ^0.5.6+1

  flutter_bloc: ^4.0.0
  equatable: ^1.2.2
  flutter_tags: ^0.4.8+2
  date_format: ^1.0.8
  flutter_inappwebview: ^4.0.0+4
  loading_more_list: 3.0.0
  pull_to_refresh: ^1.6.0
  dropdown_formfield: 0.1.2
  image_cropper: ^1.2.3
  flutter_reorderable_list: ^0.1.4
  flutter_tagging: ^2.2.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/HelveticaNeue.ttf
    - assets/fonts/HelveticaNeueMed.ttf
    - assets/images/
    - assets/json/currency.json
    - assets/videos/phone_landscape.mp4
    - assets/videos/phone_portrait.mp4
    - assets/videos/tablet_landscape.mp4
    - assets/videos/tablet_portrait.mp4
    - assets/translations/
    - assets/translations/cart_app/
    - assets/translations/commerceos/
    - assets/translations/connect_app/
    - assets/translations/custom/
    - assets/translations/pos/
    - assets/translations/product_app/
    - assets/translations/settings_app/
    - assets/translations/transaction_app/
    - assets/translations/widget_app/
    - assets/translations/transaction_app/transaction_specific/
    - assets/translations/product_app/product_list/
    - assets/translations/pos/connect/
    - assets/translations/pos/front_end/
    - assets/translations/pos/tpm/
    - assets/translations/welcome/
#    fonts:
#      - family: Helvetica Neue
#        fonts:
#          - asset: assets/fonts/HelveticaNeue.ttf
#          - asset: assets/fonts/HelveticaNeueMed.ttf
#            style: HelveticaNeue.ttf

