name: payever
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  path_provider: ^1.1.2
  page_transition: ^1.1.4
  chartjs: ^0.5.1
  flutter_sparkline: ^0.1.0
  flutter_svg: ^0.17.4
  auto_size_text: ^2.0.2+1
  intl: ^0.16.1
  url_launcher: ^5.1.0
  #webview_flutter: ^0.3.10+3
  video_player: 0.10.11+1
  cached_network_image: ^2.2.0+1
  device_info: ^0.4.0+2
  graphql_flutter: ^3.0.1
  uuid: ^2.0.2
  flutter_masked_text: ^0.8.0
  autocomplete_textfield: ^1.7.3
  numberpicker: ^1.0.0
  cron: ^0.2.2
  flutter_webview_plugin: ^0.3.5
  flutter_pagewise: ^1.2.3
  carousel_slider: ^2.1.0
  flutter_swiper: ^1.1.6
  dio: ^3.0.9
  image_picker: ^0.6.0+17
  provider: ^4.1.3
  rxdart: ^0.24.1
  oktoast: ^2.2.0
  package_info: ^0.4.0+6
  flutter_html: ^1.0.0
  blurrycontainer: ^0.0.1
  flutter_inner_drawer: ^0.5.6+1

  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  flutter_tags: ^0.4.8
  date_format: ^1.0.8
  flutter_inappwebview: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/HelveticaNeue.ttf
    - assets/fonts/HelveticaNeueMed.ttf
    - assets/images/add.svg
    - assets/images/appsicon.svg
    - assets/images/arrowposicon.svg
    - assets/images/billingicon.svg
    - assets/images/cardsicon.svg
    - assets/images/cashicon.svg
    - assets/images/closeicon.svg
    - assets/images/contact.svg
    - assets/images/dandomainicon.svg
    - assets/images/dashboardicon.svg
    - assets/images/debitooricon.svg
    - assets/images/ecicon.svg
    - assets/images/ehicon.svg
    - assets/images/facebookicon.svg
    - assets/images/feedback.svg
    - assets/images/hamburger.svg
    - assets/images/images_routes.json
    - assets/images/insertimageicon.svg
    - assets/images/jtlicon.svg
    - assets/images/languageicon.png
    - assets/images/launchicon.svg
    - assets/images/linkicon.svg
    - assets/images/loginhorizontalphone.png
    - assets/images/loginhorizontaltablet.png
    - assets/images/loginverticalphone.png
    - assets/images/loginverticaltablet.png
    - assets/images/logo-payever-white.png
    - assets/images/logout.svg
    - assets/images/magentoicon.svg
    - assets/images/mailicon.svg
    - assets/images/newpicicon.svg
    - assets/images/noimage.svg
    - assets/images/notificationicon.svg
    - assets/images/ordericon.svg
    - assets/images/oxidicon.svg
    - assets/images/payeverlogo.svg
    - assets/images/payeverlogoandname.svg
    - assets/images/payexicon.svg
    - assets/images/paymenticon.svg
    - assets/images/paymillicon.svg
    - assets/images/paypalicon.svg
    - assets/images/playvideoicon.svg
    - assets/images/plentymarketsicon.svg
    - assets/images/pos.svg
    - assets/images/posicon.svg
    - assets/images/prestashopicon.svg
    - assets/images/productsicon.svg
    - assets/images/qr.svg
    - assets/images/santandericon.svg
    - assets/images/searchicon.svg
    - assets/images/shopicon.svg
    - assets/images/shopifyicon.svg
    - assets/images/shopwareicon.svg
    - assets/images/soforticon.svg
    - assets/images/stripeicon.svg
    - assets/images/switch.svg
    - assets/images/switchericon.png
    - assets/images/timelineicon.svg
    - assets/images/transactions.svg
    - assets/images/twilioicon.svg
    - assets/images/wallpapericon.png
    - assets/images/watchedicon.svg
    - assets/images/weeblyicon.svg
    - assets/images/wooicon.svg
    - assets/images/xsinacircle.svg
    - assets/images/xticon.svg
    - assets/json/currency.json
    - assets/translations/cart_app/da.json
    - assets/translations/cart_app/de.json
    - assets/translations/cart_app/en.json
    - assets/translations/cart_app/es.json
    - assets/translations/cart_app/no.json
    - assets/translations/cart_app/sv.json
    - assets/videos/phone_landscape.mp4
    - assets/videos/phone_portrait.mp4
    - assets/videos/tablet_landscape.mp4
    - assets/videos/tablet_portrait.mp4
#    fonts:
#      - family: Helvetica Neue
#        fonts:
#          - asset: assets/fonts/HelveticaNeue.ttf
#          - asset: assets/fonts/HelveticaNeueMed.ttf
#            style: HelveticaNeue.ttf

